//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class LevelManager : MonoBehaviour{
	public GameObject currentCheckpoint;
	private PlayerController player;
	void Start(){
		player = FindObjectOfType<PlayerController> ();
	}
	void Update(){
		
	}
	public void RespawnPlayer(){
		Debug.Log ("Player Respawn");
		player.transform.position = currentCheckpoint.transform.position;
	}
}

